// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBetREPXdLKfLTBz_kEhxpINHOqbLCRY',
    appId: '1:850626662603:web:54da1ed395a7fbd6e5cb4e',
    messagingSenderId: '850626662603',
    projectId: 'yolal-e154b',
    authDomain: 'yolal-e154b.firebaseapp.com',
    storageBucket: 'yolal-e154b.firebasestorage.app',
    measurementId: 'G-5JBSMM5K4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDL_48KUV0OWfkNViNYZ1_9xhbrWroyc',
    appId: '1:850626662603:android:c117e88b3a4c4ef9e5cb4e',
    messagingSenderId: '850626662603',
    projectId: 'yolal-e154b',
    storageBucket: 'yolal-e154b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqeqww7kNj3DlbwPNGtcw6j8CEl9bP7EU',
    appId: '1:850626662603:ios:deb0e3c69e51ee42e5cb4e',
    messagingSenderId: '850626662603',
    projectId: 'yolal-e154b',
    storageBucket: 'yolal-e154b.firebasestorage.app',
    iosBundleId: 'com.example.yolAl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqeqww7kNj3DlbwPNGtcw6j8CEl9bP7EU',
    appId: '1:850626662603:ios:deb0e3c69e51ee42e5cb4e',
    messagingSenderId: '850626662603',
    projectId: 'yolal-e154b',
    storageBucket: 'yolal-e154b.firebasestorage.app',
    iosBundleId: 'com.example.yolAl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXBetREPXdLKfLTBz_kEhxpINHOqbLCRY',
    appId: '1:850626662603:web:8a6548c05fe78b49e5cb4e',
    messagingSenderId: '850626662603',
    projectId: 'yolal-e154b',
    authDomain: 'yolal-e154b.firebaseapp.com',
    storageBucket: 'yolal-e154b.firebasestorage.app',
    measurementId: 'G-Z8WNY77X84',
  );
}
